language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install tox-travis

script:
  - nosetests --with-coverage --cover-package=pipprivates
  - tox

after_success:
  - codecov
